version: '3'

services:
  db:
    container_name: db
    image: postgres
    networks:
      - user-bridge-1
    logging:
      driver: fluentd

  backend:
    container_name: backend
    build: ./backend
    command: /start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - user-bridge-1
    depends_on:
      - db
    logging:
      driver: fluentd

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend:ro
      - '/app/node_modules' # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
    ports:
      - "8080:8080"
    networks:
      - user-bridge-1
    depends_on:
      - backend
      - db
    environment:
      - NODE_ENV=development
    logging:
      driver: fluentd

networks:
  user-bridge-1:
    driver: bridge
