version: 2.1
# CircleCI
jobs:
  lint_test_coverage:
    docker:
    # The first image listed is the primary image and runs all commands
      - image: circleci/python:3.6
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DJANGO_SETTINGS_MODULE: backend.settings-circleci
    # Subsequent images listed run on a common network with the primary image
      - image: circleci/postgres:9.6.9
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r backend/requirements.txt
      # Save installed environment dependencies in cache for later steps/jobs
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Linting and Coverage
          command: |
            . .venv/bin/activate
            cd backend
            flake8
            pytest --cov --junitxml=test-reports/junit.xml
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/

workflows:
  version: 2
  lint_test:
    jobs:
      - lint_test_coverage:
          filters:
            branches:
              only: master
